# SERIAL_PORT = '/dev/tty.usbmodem241431'
# SERIAL_PORT = '/dev/tty.usbserial-FTDOMFLG'
SERIAL_PORT = '/dev/tty.usbmodem621'
SERIAL_RATE = 115200
NUM_STRINGS = 2
LIGHTS_PER_STRING = 50
NUM_LIGHTS = NUM_STRINGS * LIGHTS_PER_STRING